server:
  port: 8080
database:
  host: localhost
  port: 5432
  user: postgres
  password: 123456
  name: gogo
emailService:
  emailAddress: luadaowedsite@gmail.com
  emailPassword: qlsvgocfnsnfacxe
auth:
  secretKey: ca39d819-8726-490d-bad2-b8af7ae176e9
